version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - dependencies
    versioning-strategy: increase
    groups:
      vite:
        patterns:
          - 'vite'
          - '@vitejs/plugin-vue'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - 'react-router-dom'
      instantsearch:
        patterns:
          - '*instantsearch*'
          - '@algolia/*'
          - 'algoliasearch'
          - 'algoliasearch-helper'
          - 'search-insights'
      eslint:
        patterns:
          - '*eslint*'
          - 'globals'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-plugin-jsdoc'
